### ISSUE TITLE
Add Sublime Text 3 support

### ISSUE THREAD

**Issue by gridsane** [gl3n/sublime-php-namespace#5]
```
reloading plugin PhpNamespace.PhpNamespaceCopy
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "PhpNamespaceCopy in /home/grid/.config/sublime-text-3/Installed Packages/PhpNamespace.sublime-package", line 3, in <module>
ImportError: No module named 'namespaces'
reloading plugin PhpNamespace.namespaces
reloading plugin PhpNamespace.test_namespaces
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "test_namespaces in /home/grid/.config/sublime-text-3/Installed Packages/PhpNamespace.sublime-package", line 3, in <module>
ImportError: No module named 'namespaces'
```

**Comment by jum4** [comment]
I just pushed a new branch "ST3" with SublimeText3 full compatibility. Installation instructions are in the README.md file.
